version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /demo-dependencies
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: pip
    directory: /apps/scoring
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/scoring
    schedule:
      interval: weekly
