'use strict';

const fs = require('node:fs');
const { createClient, GitHubError, trustedRun, optionalList, safeText, githubUrl, codeRows, dependencyRows, REPORT_MARKER, AUTOFIX_MARKER, validSha } = require('./security-report-lib.cjs');

function latestRuns(runs, sha) {
  const selected = new Map();
  for (const run of runs.filter((item) => item.head_sha === sha && ['CI', 'CodeQL'].includes(item.name))) {
    const previous = selected.get(run.name);
    if (!previous || run.id > previous.id || (run.id === previous.id && run.run_attempt > previous.run_attempt)) selected.set(run.name, run);
  }
  return selected;
}

async function buildReport(client, pr) {
  const sha = pr.head.sha;
  const branchRef = `refs/heads/${pr.head.ref}`;
  const prRef = `refs/pull/${pr.number}/merge`;
  const runsResponse = await client.request('GET', `${client.prefix}/actions/runs?head_sha=${sha}&per_page=100`);
  const runs = latestRuns(runsResponse.workflow_runs || [], sha);
  const branchAnalyses = await optionalList(client, `${client.prefix}/code-scanning/analyses?ref=${encodeURIComponent(branchRef)}`);
  const prAnalyses = await optionalList(client, `${client.prefix}/code-scanning/analyses?ref=${encodeURIComponent(prRef)}`);
  const branchVerified = branchAnalyses.items.some((analysis) => analysis.commit_sha === sha && !analysis.error && analysis.tool?.name === 'CodeQL' && String(analysis.category).includes('javascript'));
  const mergeVerified = Boolean(pr.merge_commit_sha) && prAnalyses.items.some((analysis) => analysis.commit_sha === pr.merge_commit_sha && !analysis.error && analysis.tool?.name === 'CodeQL' && String(analysis.category).includes('javascript'));
  const chosenRef = branchVerified ? branchRef : prRef;
  const alerts = await optionalList(client, `${client.prefix}/code-scanning/alerts?state=open&ref=${encodeURIComponent(chosenRef)}`);
  const dependencies = await optionalList(client, `${client.prefix}/dependabot/alerts?state=open`);
  const dependencyDiff = validSha(pr.base.sha)
    ? await optionalList(client, `${client.prefix}/dependency-graph/compare/${pr.base.sha}...${sha}`)
    : { items: [], truncated: false, unavailable: 'Base SHA unavailable; dependency change comparison was not performed.' };
  const files = await client.list(`${client.prefix}/pulls/${pr.number}/files`, 1);
  const marker = AUTOFIX_MARKER.exec(pr.body || '');
  const target = marker ? Number(marker[1]) : null;
  const exactScan = branchVerified || mergeVerified;
  const checksPassed = ['CI', 'CodeQL'].every((name) => runs.get(name)?.conclusion === 'success');
  const resolved = target && exactScan && !alerts.unavailable && !alerts.truncated && checksPassed && !alerts.items.some((alert) => alert.number === target);
  const lines = [REPORT_MARKER, '## Security findings and remediation evidence', '',
    `Current PR head: **${sha}**`,
    `Compared with base: **${safeText(pr.base.ref)}**. Report generated from GitHub API evidence, not from an AI claim of success.`, '',
    '### Findings',
    `CodeQL scope: ${safeText(chosenRef)}. Current-head JavaScript analysis evidence: **${exactScan ? 'observed' : 'pending / unavailable'}**.`,
    alerts.unavailable || (alerts.items.length ? `${alerts.items.length} open alert(s) observed in this ref; showing up to 30.` : 'No open alerts returned for this ref. This is not proof of a clean scan unless current-head analysis evidence is observed.'),
    '| Alert | Rule | Severity | CWE | Location |', '|---|---|---|---|---|',
    ...codeRows(client.repository, alerts.items.slice(0, 30)), '',
    '### Dependency changes in this PR',
    dependencyDiff.unavailable || `${dependencyDiff.items.length} dependency change(s) returned; showing up to 20. GHSA identifiers below are from the dependency comparison API; CVEs are not invented when omitted.`,
    '| Package | Change | Version | License | Advisory GHSA IDs |', '|---|---|---|---|---|',
    ...dependencyDiff.items.slice(0, 20).map((item) => `| ${safeText(item.name)} | ${safeText(item.change_type)} | ${safeText(item.version)} | ${safeText(item.license)} | ${safeText((item.vulnerabilities || []).map((vulnerability) => vulnerability.advisory_ghsa_id).filter(Boolean).join(', ') || 'None supplied')} |`), '',
    '### Dependency advisories (repository default-branch inventory)',
    '**These are repository-level Dependabot alerts, not necessarily introduced or fixed by this PR.** Dependency Review checks PR-specific differences separately.',
    dependencies.unavailable || `${dependencies.items.length} open dependency alert(s) returned; showing up to 20.`,
    '| Alert | Package | GHSA | CVE | Severity | Affected range | First patched version |', '|---|---|---|---|---|---|---|',
    ...dependencyRows(client.repository, dependencies.items.slice(0, 20)), '',
    '### Proposed changes',
    ...(marker ? [`Generated by GitHub Copilot Autofix for [alert #${target}](${githubUrl(client.repository, `security/code-scanning/${target}`)}); original analyzed commit: ${marker[2]}.`] : ['No Autofix provenance marker is present. Do not assume this PR was generated by AI.']),
    ...files.items.slice(0, 30).map((file) => `- ${safeText(file.filename)}: ${safeText(file.status)}, +${Number(file.additions) || 0}/−${Number(file.deletions) || 0}. Inspect Files changed for exact repair logic.`), '',
    '### Verification for this PR head',
    ...['CI', 'CodeQL'].map((name) => {
      const run = runs.get(name);
      return run ? `- ${name}: **${safeText(run.conclusion || run.status)}** — [run ${run.id}](${githubUrl(client.repository, `actions/runs/${run.id}`)})` : `- ${name}: **pending — no run found for this head SHA**.`;
    }),
    marker ? (resolved
      ? `- Target alert #${target}: **no longer reported on the current analyzed ref, with CI and CodeQL successful.** This is scoped evidence for this target, not a claim that all repository weaknesses are fixed.`
      : `- Target alert #${target}: **repair proposed; verification incomplete or the finding remains open**.`) : '- No automated remediation result is claimed for this PR.',
    '', '### Human decision',
    '- Review the patch, relevant advisory/CWE, and remaining findings.',
    '- Confirm required checks apply to the current head before marking ready, approving, and merging.',
    '- No automatic approval, merge, deployment, or security-protection bypass is performed.',
    '- Raw secrets, tokens, secret scanning values, and source snippets are deliberately excluded.'
  ];
  if (alerts.truncated || dependencies.truncated || dependencyDiff.truncated || files.truncated || (runsResponse.total_count || 0) > 100) lines.push('', '**Coverage limit:** one or more API lists were truncated. This report is not exhaustive.');
  return lines.join('\n').slice(0, 60000);
}

async function runReport({ client, event }) {
  const workflow = event.workflow_run?.name === 'CodeQL' ? 'codeql.yml' : event.workflow_run?.name === 'CI' ? 'ci.yml' : null;
  if (!workflow) return ['Skipped unrelated workflow.'];
  const context = await trustedRun(client, event, workflow);
  if (!context || !['push', 'pull_request', 'workflow_dispatch'].includes(context.run.event)) return ['Skipped untrusted or unsupported run.'];
  const { run, repository } = context;
  const associated = await client.list(`${client.prefix}/commits/${run.head_sha}/pulls`, 1);
  if (associated.truncated) return ['Skipped: associated PR list is truncated.'];
  const candidates = associated.items.filter((pr) => pr.state === 'open' && pr.head?.repo?.id === repository.id && pr.head?.sha === run.head_sha && ['main', 'solution/hardened'].includes(pr.base?.ref));
  const notes = [];
  for (const item of candidates.slice(0, 5)) {
    const pr = await client.request('GET', `${client.prefix}/pulls/${item.number}`);
    if (pr.state !== 'open' || pr.head?.sha !== run.head_sha || pr.head.repo.id !== repository.id) continue;
    const body = await buildReport(client, pr);
    const comments = await client.list(`${client.prefix}/issues/${pr.number}/comments`);
    if (comments.truncated) { notes.push(`PR #${pr.number}: comments truncated; skipped rather than risk duplicate reports.`); continue; }
    const existing = comments.items.find((comment) => comment.user?.login === 'github-actions[bot]' && String(comment.body).startsWith(REPORT_MARKER));
    // Re-check before mutation so an old run cannot report itself as validation of a newer commit.
    const current = await client.request('GET', `${client.prefix}/pulls/${pr.number}`);
    if (current.head.sha !== run.head_sha || current.state !== 'open') { notes.push(`PR #${pr.number}: head changed; skipped stale report.`); continue; }
    if (existing && Number.isSafeInteger(existing.id)) await client.request('PATCH', `${client.prefix}/issues/comments/${existing.id}`, { body });
    else await client.request('POST', `${client.prefix}/issues/${pr.number}/comments`, { body });
    notes.push(`Updated evidence report on PR #${pr.number}.`);
  }
  if (candidates.length > 5) notes.push('Only the first five matching open PRs were processed.');
  return notes.length ? notes : ['No matching current-head, same-repository open PR; nothing to report.'];
}
async function main() {
  const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
  const client = createClient({ token: process.env.GH_TOKEN, repository: process.env.GITHUB_REPOSITORY });
  const notes = await runReport({ client, event });
  const text = `## Security report\n\n${notes.map((note) => `- ${note}`).join('\n')}\n`;
  console.log(text);
  if (process.env.GITHUB_STEP_SUMMARY) fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, text);
}
if (require.main === module) main().catch((error) => { console.error(error instanceof GitHubError ? error.message : 'Security report failed; no findings or remediation success are implied.'); process.exitCode = 1; });
module.exports = { buildReport, runReport, latestRuns };
